version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: visipakalpojumi-postgres
    environment:
      POSTGRES_DB: visipakalpojumi
      POSTGRES_USER: visipakalpojumi_user
      POSTGRES_PASSWORD: visipakalpojumi_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: